ignoreScripts: true
minimumReleaseAge: 7200
trustPolicy: no-downgrade
catalogMode: prefer
strictDepBuilds: true
blockExoticSubdeps: true

minimumReleaseAgeExclude:
  # Remove these when TS has been out for longer time
  - typescript
  - "@typescript/typescript-*"

overrides:
  undici-types: 7.16.0
  "@graphql-tools/executor-http": 3.3.0
  "@graphql-tools/executor-graphql-ws": 3.1.5
  semver: 7.8.1

catalogs:
  dev:
    oxfmt: 0.57.0
    oxlint: 1.72.0
    oxlint-tsgolint: 0.24.0
    publint: 0.3.21
    tsdown: 0.22.3
    typescript: 7.0.2

  graphql:
    "@graphql-codegen/add": 7.0.1
    "@graphql-codegen/cli": 7.1.3
    "@graphql-codegen/typescript": 6.0.2
    graphql: 17.0.2
    graphql-tag: 2.12.7

  peer:
    graphql: ">=16.0.0"
    graphql-tag: ">=2.0.0"

  types:
    "@types/node": 26.1.0
