name: GitHub Actions Security Analysis

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
      - "renovate/**"
    paths:
      - ".github/workflows/**"

permissions: {}

jobs:
  zizmor:
    uses: luxass/shared-workflows/.github/workflows/reusable-ci-security.yaml@f679de59851660fb23fd7e453ea66b9e76cb55aa # v0.11.0
    permissions:
      contents: read
      security-events: write
      id-token: write
      actions: read
    with:
      zizmor-version: v1.25.0
