name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/ci.yaml@477a19d60c922bc63fa3f926f531572cdfaf3e95 # v0.3.3
    permissions:
      contents: read
    with:
      fmt: true
      fmt-script: "fmt:check"
