name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/reusable-ci.yaml@9770f7268daf358179c45895de8becc2e8525984 # v0.14.0
    permissions:
      contents: read
    with:
      fmt: true
      fmt-script: "fmt:check"
