name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions: {}

jobs:
  ci:
    uses: luxass/shared-workflows/.github/workflows/reusable-ci.yaml@70000dc85b43fa0b5e18a731330b7f95f4e1a7fc # v0.9.0
    permissions:
      contents: read
    with:
      fmt: true
      fmt-script: "fmt:check"
