name: Update GitHub GraphQL Schema

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Run the workflow without creating a pull request
        required: false
        default: false
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    if: github.repository_owner == 'luxass'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: setup node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: lts/*

      - name: install dependencies
        run: pnpm install

      - name: download github graphql schema
        run: |
          echo "" > .env
          pnpm run schema:download
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: generate types
        run: pnpm run schema:codegen

      - name: lint with fix
        run: pnpm run lint --fix

      - name: generate diff
        id: generate-diff
        run: |
          git diff github-schema.graphql > github-schema.diff

          # if the diff is empty
          if [ ! -s github-schema.diff ]; then
            echo "No changes found in the GitHub GraphQL Schema."
            exit 0
          fi

          echo "Changes found in the GitHub GraphQL Schema:"
          {
            echo 'DIFF<<EOF'
            cat github-schema.diff
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: create pull request
        uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7.0.6
        if: ${{ github.event.inputs.dry-run != 'true' }}
        with:
          commit-message: "feat: updated github graphql schema"
          title: "feat: updated github graphql schema"
          body: |
            I found some new changes in GitHub's GraphQL Schema.

            I don't know what they changed, but I'm sure it's important.
            If you want you can go take a look yourself.

            ### Changes
            <details>
            <summary>Schema Changes</summary><br/>

            ```diff
            ${{ steps.generate-diff.outputs.DIFF }}
            ```

            <br/></details>

            I will be waiting for your approval 👋.

            This is an automated PR to update the GitHub GraphQL Schema.
          branch: update-github-graphql-schema
          add-paths: github-schema.graphql,src/github-schema.ts
          base: main
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          reviewers: luxass
